# general settings
name: SRResNet_M_sbnjrhd_250w
model_type: IRModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: MiODateset 
    meta_info: /home/notebook/data/personal/S9053103/CL_code/meta_info/MiO-meta-DF2K_300_sbnjrhd.txt #只需要给一个数据的meta文件就好了
    io_backend:
      type: disk

    gt_size: 128
    use_flip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
  val:
    name: type7
    type: PairedImageDataset
    dataroot_gt: /home/notebook/data/personal/S9053103/CL_data/CL_test/val/GT
    dataroot_lq: /home/notebook/data/personal/S9053103/CL_data/CL_test/val/LQ
    io_backend:
      type: disk


# network structures
network_g:
  type: SRResNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 16
  upscale: 1


# path
path:
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000,250000,250000,250000,250000,250000,250000,250000,250000,250000]
    restart_weights: [1,1,1,1,1,1,1,1,1,1]
    eta_min: !!float 1e-7

  total_iter: 2500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 25e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

val:
  val_freq: 25000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
