name: Classifier
model_type: ClassModel
scale: 1
num_gpu: 2
manual_seed: 0
datasets:
  train:
    name: DF2K
    type: ClassifierDataset
    meta_info: /home/notebook/data/personal/S9053103/CL_code/meta_info/CL-meta-DF2K_300_sbnjrhd.txt
    io_backend:
      type: disk
    gt_size: 256
    use_flip: true
    use_rot: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: null
  val:
    name: noise
    type: PairedImageDataset
    dataroot_gt: /home/notebook/data/personal/S9053103/CL_data/CL_test/val/GT
    dataroot_lq: /home/notebook/data/personal/S9053103/CL_data/CL_test/val/LQ
    io_backend:
      type: disk
network_g:
  type: Classifier

path:
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: true
  resume_state: ~
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: 0.0002
    weight_decay: 0
    betas:
    - 0.9
    - 0.99
  scheduler:
    type: CosineAnnealingRestartLR
    periods:
    - 250000
    - 250000
    - 250000
    - 250000
    restart_weights:
    - 1
    - 1
    - 1
    - 1
    eta_min: 1.0e-07
  total_iter: 1000000
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
logger:
  print_freq: 100
  save_checkpoint_freq: 25000.0
  use_tb_logger: true
  wandb:
    project: null
    resume_id: null
dist_params:
  backend: nccl
  port: 29500

val:
  val_freq: 25000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
